name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Install mdbook
      run: |
      - name: Install mdbook
        uses: taiki-e/install-action@v2
        with:
          tool: mdbook
      - name: Install mdbook-linkcheck2
        uses: taiki-e/install-action@v2
        with:
          tool: mdbook-linkcheck2
          fallback: cargo-install
    - name: Deploy GitHub Pages
      run: |
        mdbook build
        git worktree add gh-pages
        git config user.name "Deploy from CI"
        git config user.email ""
        cd gh-pages
        # Delete the ref to avoid keeping history.
        git update-ref -d refs/heads/gh-pages
        rm -rf *
        mv ../book/* .
        git add .
        git commit -m "Deploy $GITHUB_SHA to gh-pages"
        git push --force --set-upstream origin gh-pages
