name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install mdbook
        uses: taiki-e/install-action@v2
        with:
          tool: mdbook
      - name: Install mdbook-linkcheck2
        uses: taiki-e/install-action@v2
        with:
          tool: mdbook-linkcheck2
          fallback: cargo-install
      - name: Build
        run: mdbook build
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v5
        with:
          path: book/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v5
